# Model arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/Llama-3.2-1B-Instruct/original/tokenizer.model
  max_seq_len: 8192

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /data/users/rafiayub/torchtune_checkpoints
  checkpoint_files: [
    hf_model_0001_4.pt
  ]
  recipe_checkpoint: null
  output_dir: /tmp/Llama-3.2-1B-Instruct/
  model_type: LLAMA3_2

# Device
device: cuda
dtype: bf16
seed: 1234
log_level: INFO

# Generation arguments
max_new_tokens: 1000
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
log_every_n_samples: 10
